#!/usr/bin/env bash
# Regenerate every derived artefact from the LinkML schema (DEC-57).
# The schema is the ONE source of truth; everything this script writes is
# generated output — never hand-edit it. Re-run after editing the schema.
#
# Targets: JSON Schema + TypeScript + the human-readable HTML reference.
# (Pydantic is intentionally omitted — no Python consumer yet; add gen-pydantic
# here when one appears.)
set -euo pipefail
cd "$(dirname "$0")/.."
SCHEMA=schema/remit.yaml
VENV=${LINKML_VENV:-/tmp/linkml-venv}

# LinkML installs cleanly only in a venv here — the distro pip trips on a couple
# of legacy sdists (the install_layout quirk). See docs/project_notes/bugs.md.
if [ ! -x "$VENV/bin/linkml" ] && [ ! -x "$VENV/bin/gen-json-schema" ]; then
  echo "Bootstrapping LinkML toolchain in $VENV ..."
  python3 -m venv "$VENV"
  "$VENV/bin/pip" install --quiet --upgrade pip setuptools wheel
  # Pinned so generation is reproducible — the schema-regen CI check (ADR-0011)
  # regenerates and fails on any diff, so the toolchain version must be fixed
  # (linkml-runtime too: it drives the generators' output).
  "$VENV/bin/pip" install --quiet "linkml==1.11.1" "linkml-runtime==1.11.1"
fi
V="$VENV/bin"

mkdir -p schema/gen
echo "→ JSON Schema  schema/gen/remit.schema.json"
"$V/gen-json-schema" "$SCHEMA" > schema/gen/remit.schema.json
echo "→ TypeScript   schema/gen/remit.ts"
"$V/gen-typescript" "$SCHEMA" > schema/gen/remit.ts
echo "→ HTML ref     site/data-model/index.html"
"$V/python" schema/build-reference.py

# --- GENERATED banners (ADR-0011) ----------------------------------------------
# Stamp every derived artefact "do not edit", added here so the marker survives
# every regeneration (the generators above rewrite each file from scratch, so the
# banner is re-applied once per run — idempotent). The schema-regen CI check then
# enforces that the committed files match this script's output byte-for-byte.
echo "→ banners      schema/gen/*, site/data-model/index.html"

TS=schema/gen/remit.ts
{ cat <<'BANNER'
// @generated — DO NOT EDIT.
// Generated by schema/generate.sh from the LinkML schema (schema/remit.yaml, DEC-57).
// Edit the schema modules under schema/ and re-run `bash schema/generate.sh`.
// Drift from the schema is caught by the schema-regen CI check (ADR-0011).

BANNER
  cat "$TS"; } > "$TS.tmp" && mv "$TS.tmp" "$TS"

# JSON has no comments — insert a "$comment" as the first key (textual, so the rest
# of gen-json-schema's output is left byte-for-byte unchanged).
JSON=schema/gen/remit.schema.json
JSON_MSG='@generated — DO NOT EDIT. Generated by schema/generate.sh from the LinkML schema (schema/remit.yaml, DEC-57); edit the schema and re-run it. Drift is caught by the schema-regen CI check (ADR-0011).'
{ head -n 1 "$JSON"
  printf '    "$comment": "%s",\n' "$JSON_MSG"
  tail -n +2 "$JSON"; } > "$JSON.tmp" && mv "$JSON.tmp" "$JSON"

HTML=site/data-model/index.html
{ printf '%s\n' '<!-- @generated — DO NOT EDIT. Generated by schema/build-reference.py from the LinkML schema (schema/remit.yaml, DEC-57) via schema/generate.sh. Drift is caught by the schema-regen CI check (ADR-0011). -->'
  cat "$HTML"; } > "$HTML.tmp" && mv "$HTML.tmp" "$HTML"

echo "Done."
